site_name: sia20-pose-follow
site_description: Velocity control and pose following documentation.
site_author: harumo

# the color is changed when mkdocs build
theme: 
  name: 'readthedocs'

copyright: Copyright (c) 2019


markdown_extensions:
- def_list
- fenced_code
- admonition
- wikilinks
- pymdownx.arithmatex

extra_javascript:
 - 'http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'
 - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
 - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
